require 'minitest/autorun'
require 'sinatra'
require 'rack/test'

$:.unshift File.expand_path '../', File.dirname(__FILE__)
require 'lib/attr'
require 'lib/wiki'
require 'lib/page'
require 'lib/auth'
require 'lib/md5'
require 'lib/config'
require 'lib/png'
require 'lib/keyword'
require 'lib/pair'
require 'lib/rss'
require 'lib/search'
require 'lib/time'
require 'controllers/gyazz'
