def contenttype(ext)
  _contenttype={}
  _contenttype['.txt'] = 'text/plain'
  _contenttype['.csv'] = 'text/csv'
  _contenttype['.tsv'] = 'text/tab-separated-values'
  _contenttype['.doc'] = 'application/msword'
  _contenttype['.xls'] = 'application/vnd.ms-excel'
  _contenttype['.ppt'] = 'application/vnd.ms-powerpoint'
  _contenttype['.pdf'] = 'application/pdf'
  _contenttype['.xdw'] = 'application/vnd.fujixerox.docuworks'
  _contenttype['.html'] = 'text/html'
  _contenttype['.html'] = 'text/html'
  _contenttype['.css'] = 'text/css'
  _contenttype['.js'] = 'text/javascript'
  _contenttype['.hdml'] = 'text/x-hdml'
  _contenttype['.jpg'] = 'image/jpeg'
  _contenttype['.jpeg'] = 'image/jpeg'
  _contenttype['.png'] = 'image/png'
  _contenttype['.gif'] = 'image/gif'
  _contenttype['.bmp'] = 'image/bmp'
  _contenttype['.ai'] = 'application/postscript'
  _contenttype['.mp3'] = 'audio/mpeg'
  _contenttype['.m4a'] = 'audio/mp4'
  _contenttype['.wav'] = 'audio/x-wav'
  _contenttype['.mid'] = 'audio/midi'
  _contenttype['.midi'] = 'audio/midi'
  _contenttype['.mmf'] = 'application/x-smaf'
  _contenttype['.mpg'] = 'video/mpeg'
  _contenttype['.mpeg'] = 'video/mpeg'
  _contenttype['.wmv'] = 'video/x-ms-wmv'
  _contenttype['.swf'] = 'application/x-shockwave-flash'
  _contenttype['.3g2'] = 'video/3gpp2'
  _contenttype['.zip'] = 'application/zip'
  _contenttype['.lha'] = 'application/x-lzh'
  _contenttype['.lzh'] = 'application/x-lzh'
  _contenttype['.tar'] = 'application/x-tar'
  _contenttype['.tgz'] = 'application/x-tar'
  _contenttype['.exe'] = 'application/octet-stream'
  _contenttype[''] = ''

  return _contenttype[ext]
end
