#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# 古いGyazzデータを新しいものに変換する
#
# % ruby convert olddir newdir
#

require 'digest/md5'
require 'sdbm'

$:.unshift File.expand_path '../lib', File.dirname(__FILE__)

olddir = ARGV.shift
newdir = ARGV.shift

exit if olddir.nil? || newdir.nil?

def command(s)
  puts s
  system s if s =~ /mkdir/
end

class String
  def md5
    Digest::MD5.new.hexdigest(self).to_s
  end
end

wikis = Dir.open(olddir).find_all { |file|
  file =~ /^[\da-f]{32}$/
}
wikis.each { |wikiid|
  system "ruby convert1 #{olddir} #{newdir} #{wikiid}"
}
