#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# 管理コマンド
#
# % gyazz list wikiname
#   wikinameのページをリストする
# % gyazz replace wikiname fromstr tostr
#   wikinamae内の全ページ内の文字列fromstrをtostrに置換する
#

$:.unshift File.expand_path '../lib', File.dirname(__FILE__)

require 'uri'
require 'lib'
require 'config'
require 'pair'
require 'readdata'
require 'writedata'
require 'keyword'

cmd = ARGV.shift
if cmd.nil?
  puts "% gyazz cmd {args}"
  exit
end

if cmd == 'list' then
  name = ARGV.shift
  exit unless name

  top = Gyazz.topdir(name)
  pair = Pair.new("#{top}/pair")
  titles = pair.keys
  pair.close

  puts titles
elsif cmd == 'replace' then
  name = ARGV.shift
  from = ARGV.shift
  to = ARGV.shift
  exit if !name || !from || !to
  puts from

  top = Gyazz.topdir(name)
  pair = Pair.new("#{top}/pair")
  titles = pair.keys
  pair.close

  titles.each { |title| 
    data = readdata(name,title)
    data.gsub!(from,to)
    writedata(name,title,data)
  }
end
